sudo: false
dist: trusty

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 5

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - flags="--no-interaction --no-progress --prefer-dist"

install:
  - composer install $flags

script:
  - vendor/bin/phpunit
